### ISSUE TITLE
Official releases & publishing on drupal.org

### ISSUE THREAD

**Issue by mh-nichts** [OpenAgenda/drupal#1]
Hello, I'm part of the team working on SQY to use this module, so I'm going to file some issues as discussed per email :)

First one, is it possible to have official releases with tags ? 
Currently we have to work directly with different branches depending on the Drupal version, it's not really the "normal" process for that kind of modules and could lead to errors during development (if elements changed on the master branch for example).

A further step would also be to publish it on drupal.org, so it could be found on the [modules list](https://www.drupal.org/project/project_module?f%5B0%5D=&f%5B1%5D=&f%5B2%5D=&f%5B3%5D=&f%5B4%5D=sm_field_project_type%3Afull&f%5B5%5D=&f%5B6%5D=&text=openagenda&solrsort=iss_project_release_usage+desc&op=Search).

**Comment by kaore** [comment]
We don't plan to change the way the module is updated for the time being. We have published it on drupal.org where you should find the tags you requested: https://www.drupal.org/project/openagenda
