### ISSUE TITLE
Event source url

### ISSUE THREAD

**Issue by koposzek** [OpenAgenda/drupal#10]
The previous versions of the module returned in the Event item his source url (something like www.openagenda.com/{agenda_id}/events/{event_slug}) under the "canonicalUrl" parameter which is no more the case. Is it possible to bring it back please ?

**Comment by kaore** [comment]
You can rebuild this link easily using the identifier present in the originAgenda. The link can take this form: https://openagenda.com/agendas/{agendaUid}/events/{eventUid}

**Comment by koposzek** [comment]
Ok, indeed it works. Thanks.
