### ISSUE TITLE
Event - categories and tags

### ISSUE THREAD

**Issue by koposzek** [OpenAgenda/drupal#11]
In the new version, the Categories and Tags are sent in an ID format and not as labels (and by the way the variable tags is sent as "**tags-test**".
Is there a possibility to go back to the previous state of those items as it is no use for us to display the IDs ?

Current format:
`
"tags-test" => [
    0 => 157
    1 => 128
    2 => 129
  ]
`

**Comment by kaore** [comment]
Hi, an update is under way to present the labels together with the ids so you can use them in your templates. It should be published in the coming days

**Comment by tchoucky61** [comment]
Openagenda PHP SDK has been updated (1.1.0) to include additional field labels to events such as categories.
Update it running composer update openagenda/sdk-php

**Comment by tchoucky61** [comment]
Next opengaenda Drupal module version will include this dependency update (next week).

**Comment by kaore** [comment]
@koposzek the latest version of the module provides you with the label together with the id. The id allows you to link back to a filtered list view

**Comment by koposzek** [comment]
Great ! :+1:
