### ISSUE TITLE
Filter block - Tags and Categories

### ISSUE THREAD

**Issue by koposzek** [OpenAgenda/drupal#12]
There is no more filter block with Tags and Categories.
Is it on purpose ? Since the filter still exists on the openagenda.com lists ?

**Comment by kaore** [comment]
Yes. These are now additional fields which codes you can find under the Form/Formulaire tab of the administration of your calendar. You can use blocks presented the administration of the module to place filters on the main calendar page

**Comment by tchoucky61** [comment]
Openagenda PHP SDK has been updated (1.1.0) to include additional field labels to events such as categories.
Update it running `composer update openagenda/sdk-php`

**Comment by koposzek** [comment]
I meant that we have no more Categories/Tags filter block available in the Drupal module (but the filter is available on the openagenda.com site, example: https://openagenda.com/sqy?lang=fr)

**Comment by tchoucky61** [comment]
Indeed. But this filter is custom field based. As far as I know, such oa react filter (used by Drupal module) is not implemented yet.

**Comment by kaore** [comment]
@koposzek this block should be implemented soon, we'll get back to you here when it is available.

**Comment by tchoucky61** [comment]
@koposzek, Drupal module has been updated to 3.2.0. This release includes additional field Filter :

`composer update drupal/openagenda`

**Comment by koposzek** [comment]
Great, that's what I was looking for. Thanks !
