### ISSUE TITLE
Filter - Map error 500

### ISSUE THREAD

**Issue by koposzek** [OpenAgenda/drupal#13]
When I put the Map filter on my agenda page I've got an error 500 in the console and it is not rendered.
The error message:

`OpenAgendaSdk\OpenAgendaSdkException: Server error: `GET https://api.openagenda.com/v2/agendas/xxxxx/events?aggregations%5B0%5D%5Btype%5D=geohash&aggregations%5B0%5D%5Bsize%5D=2000&aggregations%5B0%5D%5Bzoom%5D=18&aggregations%5B0%5D%5Bradius%5D=40&geo%5BnorthEast%5D%5Blat%5D=48.922499263758255&geo%5BnorthEast%5D%5Blng%5D=-78.28125&geo%5BsouthWest%5D%5Blat%5D=48.922499263758255&geo%5BsouthWest%5D%5Blng%5D=81.09375&size=0&detailed=1&key=2e2cb6354c4947d991b07717ffe6119e` resulted in a `500 Internal Server Error` response: {"message":"server trouble.. send an short mail to support to receive detailed feedback: support@openagenda.com"} in OpenAgendaSdk\HttpClient->request() (line 95 of /var/www/html/vendor/openagenda/sdk-php/src/HttpClient.php).`

(where `xxxx` = agenda uid)

@update Putting the DateRange filter block on the same page is fixing the problem, I have no idea why.

**Comment by kaore** [comment]
Can you provide the identifier of the agenda which returns this error?

**Comment by koposzek** [comment]
Well with the new version of the module it's not there anymore. I don't know if it was fixed or it was just a temporary error.
