### ISSUE TITLE
Handle past events

### ISSUE THREAD

**Issue by mh-nichts** [OpenAgenda/drupal#6]
As far as we know, currently the only way to display past events is to select a past date in the calendar, but that is too specific : that only displays the events on that particular date.
So, is there a way to display only past (finished) events, or could that be added to the filter possibilities ?

**Comment by kaore** [comment]
The version of the search engine used behind the module does not allow to display past events exclusively. It is only possible to include past events to the selection by adding `?oaq[passed]=1`

**Comment by kaore** [comment]
You can also specify a range of past dates oaq[from]=...&oaq[to]=... but this will include all events having timings in that period, regardless of the presence of upcoming timings

**Comment by tchoucky61** [comment]
Openagenda [3.1.1](https://www.drupal.org/project/openagenda/releases/3.1.1) includes a relative date filter block.
