### ISSUE TITLE
Tag numbers versus results count

### ISSUE THREAD

**Issue by mh-nichts** [OpenAgenda/drupal#7]
We have a difference between the number displaying in the tags, and the number of results displayed when choosing that precise tag.
For example here : https://www.saint-quentin-en-yvelines.fr/fr/agenda-de-saint-quentin-en-yvelines?oaq%5Btags%5D%5B0%5D=culture
The "Culture" tag in the filters indicates "778", although when choosing that tag, there are only 392 results in the list.

Do you know what could cause this kind of difference ?

**Comment by kaore** [comment]
Yes, the current version of filters only handles uniquely named tags, but in the current agenda you have two groups with the same value "culture" (Tags, Catégories). An upcoming update will fix this use case by the end of the year. In the meantime, one of the 'culture' tags could be slightly adjusted to adjust the total

**Comment by kaore** [comment]
The latest release fixes this issue. Please note that this is a breaking change, all filter blocks need to be replaced as filter totals are now calculated on the server side.
