### ISSUE TITLE
Title in breadcrumb

### ISSUE THREAD

**Issue by mh-nichts** [OpenAgenda/drupal#8]
On an event detail page, the title appearing in the breadcrumb isn't the same as the "real event title" : it's sometimes a "short title" with a numbered id, see example here : https://www.saint-quentin-en-yvelines.fr/fr/agenda-de-saint-quentin-en-yvelines/a-la-lisiere-6927635?oac=eyJpbmRleCI6MSwidG90YWwiOjM0OH0%3D&amp;nbsp;

Or sometimes it seems to be the "real title", except the accents aren't there : https://www.saint-quentin-en-yvelines.fr/fr/agenda-de-saint-quentin-en-yvelines/exposition-viens-jouer-dehors-1968-1978-la-nouvelle-ere-des-jeux?oac=eyJpbmRleCI6MCwidG90YWwiOjQxNn0%3D

Is there something handled by the module for this ?

**Comment by kaore** [comment]
The slug (title in the URL) derives from the title. Event slugs have to be unique: when the title has already been used by another event, a random number is added to the slug.

The same slug is used on https://openagenda.com, it cannot be edited by the Drupal module.
